### ISSUE TITLE
Is there support for VariableSets ?

### ISSUE THREAD

**Issue by maclarensg** [hashicorp/go-tfe#312] opened 2022-02-16 06:53 UTC
Hi,

Would be great if this SDK would include querying and creating VariableSets and setting VariableSets to workspaces.

**Comment by maclarensg** [comment] 2022-02-16 07:14
I see there is a Api support 
https://www.terraform.io/cloud-docs/api-docs/variable-sets

**Comment by chrisarcand** [comment] 2022-02-16 14:53
Closing as a duplicate of #284

**Closed by chrisarcand** 2022-02-16 14:53 UTC
